### ISSUE TITLE
Feature Request: "Unlock full menu" option in cheats

### ISSUE THREAD

**Issue by Bluscream** [leopard20/All-In-One-Command-Menu#10]
It would be great if there was a possibility to unlock all menus that are only hidden through privileges (like the HC menu) in the cheats menu

> P.S. Where do i sign up for the closed beta of the Better AI thingy, i'm especially thrilled to test the (even when buggy) new building path finding ^^

**Comment by Leopard20** [comment]
The HC menu is not hidden. You just switch to HC mode (Ctrl + Space) and reopen the menu (Y).
If it cannot be accessed, the menu item "Make units playable" becomes replaced with a new one called "HC Menu".

There's currently no release for the Super AI, and I'm working on this alone. I might make it available for testing when it's more complete.

**Comment by Bluscream** [comment]
Thanks
