### ISSUE TITLE
Question: How to switch back to initial unit?

### ISSUE THREAD

**Issue by Bluscream** [leopard20/All-In-One-Command-Menu#12]
When i started playing with the "make other units playable" feature i could not find any way to switch back except killing myself and then instead of restarting the mission, using "switch to another unit". Is there a better way of doing it?

**Comment by Leopard20** [comment]
Go to your controls and under Common, look for Team Switch. By default it is bound to "U". So just press U and switch units.

**Comment by Bluscream** [comment]
Thanks a lot ^^ i didnt expect that to be a non-mp feature :D
