### ISSUE TITLE
Feature Request: Submenu setting

### ISSUE THREAD

**Issue by Bluscream** [leopard20/All-In-One-Command-Menu#13]
***Feature Description:***

A addon setting that would add all the possible submenus to the main menu itself instead of using the extra hotkeys (Like 1-8 submenus in the main menu)

I know the menu would get quite full then but that's why i'd prefer it as a optional addon setting. It would help to free some keys and help if you don't remember all the hotkeys ^^

**Comment by Leopard20** [comment]
It's not really possible. All menus can have up to 12 elements at one time. I don't think I can add all submenus to the main menu. Plus it requires a lot of work to rewrite this.

**Comment by Bluscream** [comment]
Wouldnt it be possible like this?

- Main menu
  - any submenu that has a slot free
    - new menu that contains the 1-8 menus (which could just call them how the keybinds would call them)

**Comment by Leopard20** [comment]
Hold on. By submenus do you mean the "custom command menus" (move, target, formation, etc.)? If so, I can add them. I thought you mean putting the submenu of each menu directly in the main menu!

**Comment by Bluscream** [comment]
yes, i meant these formation, mount, etc.. menus ^^

**Comment by Bluscream** [comment]
?

**Comment by Leopard20** [comment]
Added in the latest release

**Comment by Bluscream** [comment]
Weird, i dont see any new commits OwO

P.S. Also how does one enable the setting?

**Comment by Leopard20** [comment]
I haven't updated the source code since AIO Menu classic. If you un-PBO the latest version, you'll notice that the entire mod structure has changed.
I'm not in the mood for rebasing the repository.

There's no setting. I've replaced "Make units playable" with a new submenu.

**Comment by Bluscream** [comment]
Am i allowed to rebase and PR it or do you want the new one to stay "closed-src"

**Comment by Bluscream** [comment]
Let's say fixed in https://github.com/leopard20/All-In-One-Command-Menu/releases/tag/v1.1.4-Beta then :)

**Comment by Leopard20** [comment]
If you feel like it why not?! I appreciate it.
