### ISSUE TITLE
Error message when asking AI to disassemble a emplacement

### ISSUE THREAD

**Issue by 6komodo6** [leopard20/All-In-One-Command-Menu#31]
**_Describe the bug:_**
They are able to disassemble the emplacement but a bug appears on screen
**_Steps to reproduce:_**
Ask AI to disassemble an MG emplacement
**_Additional context:_**
![ArmA 3 Screenshot 2024 03 28 - 15 08 47 44](https://github.com/Leopard20/All-In-One-Command-Menu/assets/159446886/e4925fee-337d-40fa-aa89-c8a29a8ab0a0)

**Comment by Leopard20** [comment]
Thanks, fixed

**Comment by 6komodo6** [comment]
thnx Leo
