### ISSUE TITLE
Switching to another playable unit renders the former unresponsive 

### ISSUE THREAD

**Issue by 6komodo6** [leopard20/All-In-One-Command-Menu#33]
**_Describe the bug:_**
If you have multiple playable units and you switch to one, the initial you switched from will be not move and FSM won't take over until you issue an order manually.
**_Steps to reproduce:_**
Add playable units and switch to any of them
**_Additional context:_**
Having AI be somewhat competent and reacting to fire while I switch to the sniper for example would be appreciated, as I know this is mostly base Arma issue

**Comment by 6komodo6** [comment]
Sorry this wasn't because of your mod its apparently a vanilla arma bug

**Comment by Leopard20** [comment]
I see. Thanks
