### ISSUE TITLE
Feature Request: Drive to waypoint toggle

### ISSUE THREAD

**Issue by Bluscream** [leopard20/All-In-One-Command-Menu#9]
***Feature Description:***

It would be super neat if there was a simple toggle that, if enabled would automatically instruct the driver to drive to your current waypoint (the marker set with SHIFT+Click on the map) while enabled.

**Comment by Leopard20** [comment]
Isn't it possible to do this by just selecting the unit and clicking on the map (or pressing spacebar)?!

**Comment by Bluscream** [comment]
Selecting the unit is the thing that bothers me, i would love for it to automatically detect which unit is currently driver and instruct that one to do that rather than remembering all the numbers :D
